// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAinLSTG_8ePt6I28c_2AzVDNneW5n_-QQ',
    appId: '1:251371728481:web:5f6c03029c6848d1298420',
    messagingSenderId: '251371728481',
    projectId: 'projetmobile-95993',
    authDomain: 'projetmobile-95993.firebaseapp.com',
    storageBucket: 'projetmobile-95993.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiDFVVA_skb4tgRhJNGlnNWFivu_Brgrk',
    appId: '1:251371728481:android:446ef892568edcf1298420',
    messagingSenderId: '251371728481',
    projectId: 'projetmobile-95993',
    storageBucket: 'projetmobile-95993.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8kKSZQ5CmAG-kr6z8sHIKywhiIq_7ywg',
    appId: '1:251371728481:ios:57920bc620864e2b298420',
    messagingSenderId: '251371728481',
    projectId: 'projetmobile-95993',
    storageBucket: 'projetmobile-95993.appspot.com',
    iosBundleId: 'com.example.projetmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8kKSZQ5CmAG-kr6z8sHIKywhiIq_7ywg',
    appId: '1:251371728481:ios:57920bc620864e2b298420',
    messagingSenderId: '251371728481',
    projectId: 'projetmobile-95993',
    storageBucket: 'projetmobile-95993.appspot.com',
    iosBundleId: 'com.example.projetmobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAinLSTG_8ePt6I28c_2AzVDNneW5n_-QQ',
    appId: '1:251371728481:web:c95b3c8f057f0380298420',
    messagingSenderId: '251371728481',
    projectId: 'projetmobile-95993',
    authDomain: 'projetmobile-95993.firebaseapp.com',
    storageBucket: 'projetmobile-95993.appspot.com',
  );

}