// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdoYb4NqFt4YgMhnwG4-1AaxwaiqE0rl0',
    appId: '1:63215065631:web:ddb7959b0115b722ae132a',
    messagingSenderId: '63215065631',
    projectId: 'projetmobile-27ead',
    authDomain: 'projetmobile-27ead.firebaseapp.com',
    storageBucket: 'projetmobile-27ead.appspot.com',
    measurementId: 'G-308Q4FHTC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzLJOH-YetkduQ6pJXiuHQ8vLmBFovJs4',
    appId: '1:63215065631:android:c3fd509809ec2ee4ae132a',
    messagingSenderId: '63215065631',
    projectId: 'projetmobile-27ead',
    storageBucket: 'projetmobile-27ead.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8zB2W9f9CnWNrcxZvYLaqlFRvZcFjg28',
    appId: '1:63215065631:ios:dbd6cea92e8150b2ae132a',
    messagingSenderId: '63215065631',
    projectId: 'projetmobile-27ead',
    storageBucket: 'projetmobile-27ead.appspot.com',
    iosBundleId: 'com.example.projetmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8zB2W9f9CnWNrcxZvYLaqlFRvZcFjg28',
    appId: '1:63215065631:ios:834e4e0ca8292bb8ae132a',
    messagingSenderId: '63215065631',
    projectId: 'projetmobile-27ead',
    storageBucket: 'projetmobile-27ead.appspot.com',
    iosBundleId: 'com.example.projetmobile.RunnerTests',
  );
}
